#!/usr/bin/python3
"""Defines the Base class, the foundation for all other classes.

This module contains the Base class, which handles the id attribute
shared by all future classes, and provides serialization and
deserialization helpers via JSON.
"""
import json
import csv


class Base:
    """Represent the base class for all other classes in this project."""

    __nb_objects = 0

    def __init__(self, id=None):
        """Initialize a new Base instance.

        Args:
            id (int): The identity of the new instance. If None, the
                id is auto-generated by incrementing a class counter.
        """
        if id is not None:
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects

    @staticmethod
    def to_json_string(list_dictionaries):
        """Return the JSON string representation of a list of dicts.

        Args:
            list_dictionaries (list): A list of dictionaries.

        Returns:
            str: The JSON string representation, or "[]" if the list
                is None or empty.
        """
        if list_dictionaries is None or len(list_dictionaries) == 0:
            return "[]"
        return json.dumps(list_dictionaries)

    @classmethod
    def save_to_file(cls, list_objs):
        """Write the JSON string representation of a list of objects
        to a file.

        Args:
            list_objs (list): A list of instances that inherit from
                Base.
        """
        filename = "{}.json".format(cls.__name__)
        if list_objs is None:
            list_objs = []
        list_dicts = [obj.to_dictionary() for obj in list_objs]
        with open(filename, mode="w") as jsonfile:
            jsonfile.write(cls.to_json_string(list_dicts))

    @staticmethod
    def from_json_string(json_string):
        """Return a list of dictionaries represented by a JSON string.

        Args:
            json_string (str): A JSON string representing a list of
                dictionaries.

        Returns:
            list: The Python list represented by json_string, or an
                empty list if json_string is None or empty.
        """
        if json_string is None or len(json_string) == 0:
            return []
        return json.loads(json_string)

    @classmethod
    def create(cls, **dictionary):
        """Return an instance with all attributes already set.

        Args:
            **dictionary (dict): Key/value pairs of attributes to
                initialize the new instance with.

        Returns:
            An instance of cls with attributes set from dictionary.
        """
        if cls.__name__ == "Rectangle":
            dummy = cls(1, 1)
        else:
            dummy = cls(1)
        dummy.update(**dictionary)
        return dummy

    @classmethod
    def load_from_file(cls):
        """Return a list of instances loaded from a JSON file.

        Returns:
            list: A list of instances of cls, deserialized from
                <cls.__name__>.json. Returns an empty list if the
                file doesn't exist.
        """
        filename = "{}.json".format(cls.__name__)
        try:
            with open(filename, mode="r") as jsonfile:
                list_dicts = cls.from_json_string(jsonfile.read())
                return [cls.create(**d) for d in list_dicts]
        except IOError:
            return []

    @classmethod
    def save_to_file_csv(cls, list_objs):
        """Write the CSV representation of a list of objects to a file.

        Args:
            list_objs (list): A list of instances that inherit from
                Base.
        """
        filename = "{}.csv".format(cls.__name__)
        with open(filename, "w", newline="") as csvfile:
            if list_objs is None or list_objs == []:
                csvfile.write("[]")
                return
            if cls.__name__ == "Rectangle":
                fieldnames = ["id", "width", "height", "x", "y"]
            else:
                fieldnames = ["id", "size", "x", "y"]
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            for obj in list_objs:
                writer.writerow(obj.to_dictionary())

    @classmethod
    def load_from_file_csv(cls):
        """Return a list of instances loaded from a CSV file.

        Returns:
            list: A list of instances of cls, deserialized from
                <cls.__name__>.csv. Returns an empty list if the
                file doesn't exist.
        """
        filename = "{}.csv".format(cls.__name__)
        try:
            with open(filename, "r", newline="") as csvfile:
                if cls.__name__ == "Rectangle":
                    fieldnames = ["id", "width", "height", "x", "y"]
                else:
                    fieldnames = ["id", "size", "x", "y"]
                reader = csv.DictReader(csvfile, fieldnames=fieldnames)
                list_dicts = [
                    {k: int(v) for k, v in d.items()} for d in reader
                ]
                return [cls.create(**d) for d in list_dicts]
        except IOError:
            return []
